---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 19733.
--- DateTime: 2024/11/21 0:32
---

local voucherKey="seckillVoucher:"..ARGV[1]
local userKey="order:"..ARGV[1]
local a=redis.call('get',voucherKey)
if not a then
    return -1;
end
---判断库存是否充足
if(tonumber(a)<=0) then
    return 1
end
---检测一人一单
local flag=redis.call('sadd',userKey,ARGV[2])
if(flag==0) then
    return 2;
end
redis.call('incrby',voucherKey,-1)
return 0